### ISSUE TITLE
BGA with Staggered Pins

### ISSUE THREAD

**Issue by tiborgats** [qeda/qeda#28]
Many new WLCSP packages are staggered pin BGAs, it would be nice if QEDA will support it. They already have IPC-7351C name definition, starting with `BGAS`.
Some examples:
- page 8 of http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-42493-ATBTLC1000-WLCSP-SOC_Datasheet.pdf
- last page of http://www.onsemi.com/pub_link/Collateral/BELASIGNA300-D.PDF

**Comment by shamil-ru** [comment]
It is possible to do it at the moment. For example:

```yaml
# ...
pinout:
  GPIO:
    LP_GPIO_0-3: D5, F7, G6, H7
    LP_GPIO_8-13: J6, H5, J4, F5, G4, D3
    AO_GPIO_0: B1
    GPIO_MS_1: F3

  XTAL:
    XO_P: A4
    XO_N: B5

  RTC:
    RTC_CLK_P: C2
    RTC_CLK_N: D1

  RFIO: B7
  CHIP_EN: E2

  LP_LDO_OUT_1P2: F1
  VSW: J2
  TPP: C4

  VDDIO: A2
  VDDIO_SWITCH: B3
  VDD_VCO/VDD_SXDIG: A6
  VDD_RF: C6
  VDD_AMS: E6
  VDDC_PD4: H1
  VBATT_BUCK: G2

  VSS: E4
  RFGND: D7
  GND_BUCK: H3
# ...
housing:
  pattern: BGA

  bodyWidth: 2.262
  bodyLength: 2.142
  height: 0.483-0.541
  rowCount: 9
  columnCount: 7
  horizontalPitch: 0.2825
  verticalPitch: 0.2125
  leadDiameter: 0.188-0.248
```

produces:

![bgas](https://cloud.githubusercontent.com/assets/4997723/23328725/85ced0fa-fb42-11e6-898b-94251299a65c.png)
