### ISSUE TITLE
symbol generation

### ISSUE THREAD

**Issue by steel-ne** [qeda/qeda#3]
Attached test.yaml expected to generate 8-pin IC symbol: left side pins 1-4, right side others. But it generates only 4 pins.
[test.yaml.txt](https://github.com/qeda/qeda/files/466509/test.yaml.txt)
![test](https://cloud.githubusercontent.com/assets/195610/18424430/3383e0cc-78b8-11e6-90e4-de4fb3c48501.png)

**Comment by shamil-ru** [comment]
Thank you for information. There was a bug indeed. Now this bug is fixed (see v0.2.3).

But note that `PF2-3` and `PC2-3` are not grouped together because they are not groups but pin lists.

My opinion that it is better to group pins by their primary function. Alternative pin functions are not needed to be combined in groups.

``` yaml
pinout:
  # Primary pin functions
  PORTC:
    PC0-3: 1, 2, 7, 8
  PORTF:
    PF0-3: 3-6

  # Alternative pin functions
  OSC_IN: 1
  OSC_OUT: 2
  OSC32_IN: 3
  OSC32_OUT: 4

schematic:
  symbol: IC
  left: PORTC
  right: PORTF
```

This will produce following symbol:
![test](https://cloud.githubusercontent.com/assets/4997723/18429165/258cc508-78e3-11e6-807b-47bfbd98e851.png)
