### ISSUE TITLE
FET symbol broken

### ISSUE THREAD

**Issue by tiborgats** [qeda/qeda#34]
I tried to create a BGA housed FET in QEDA, but I get a broken schematic symbol:
![image](https://user-images.githubusercontent.com/16302588/29168843-10360fb8-7dd1-11e7-9030-dc1d9152b0aa.png)

It would be nice to have `G`, `D`, `S` signs on the legs instead of numbering, as for the BGA component numbering is ugly and not useful at all. Also please allow substrate (thermal, not connected or connected to Source) pads.

I made a custom housing as the BGA pattern does not allow custom pad numbering scheme.

The `epc2047.yaml` is this:
```
name: EPC2047
description: eGaN FET, 200V, 10mΩ
datasheet: http://epc-co.com/epc/Portals/0/epc/documents/datasheets/EPC2047_preliminary.pdf
keywords: eGaN, GaN, FET

pinout:
  G: 1
  D: 3, 4, 5, 9, 10, 11
  S: 2, 6, 7, 8, 12, 14
  sb: 13 # = substrate

properties:
  in: G
  passive: S, D, sb

schematic:
  symbol: FET
  options: n, diode

housing:
#  pattern: BGA # WLCSP
#  leadCount: 14 # 14
#  rowCount: 3
#  columnCount: 5
#  horizontalPitch: 1.0
#  verticalPitch: 0.5
#  leadDiameter: 0.330
  pattern: custom
  bodyLength: 1.570-1.630
  bodyWidth: 4.570-4.630
  height: 0.790
  padDiameter: 0.330
  padWidth: 0.330 # workaround for QEDA bug, can be deleted later
  padHeight: 0.330 # workaround for QEDA bug, can be deleted later
  padPosition: -2, -0.5, -2, 0.5, -1, -0.5, -1, 0, -1, 0.5, 0, -0.5, 0, 0, 0, 0.5, 1, -0.5, 1, 0, 1, 0.5, 2, -0.5, 2, 0, 2, 0.5
```
